cmake_minimum_required(VERSION 3.12)
if(NOT WIN32)
    if($ENV{CLICOLOR} OR $ENV{CLICOLOR_FORCE})
        string(ASCII 27 Esc)
        set(ColourReset "${Esc}[m")
        set(ColourBold  "${Esc}[1m")
        set(Red         "${Esc}[31m")
        set(Green       "${Esc}[32m")
        set(Yellow      "${Esc}[33m")
        set(Blue        "${Esc}[34m")
        set(Magenta     "${Esc}[35m")
        set(Cyan        "${Esc}[36m")
        set(White       "${Esc}[37m")
        set(BoldRed     "${Esc}[1;31m")
        set(BoldGreen   "${Esc}[1;32m")
        set(BoldYellow  "${Esc}[1;33m")
        set(BoldBlue    "${Esc}[1;34m")
        set(BoldMagenta "${Esc}[1;35m")
        set(BoldCyan    "${Esc}[1;36m")
        set(BoldWhite   "${Esc}[1;37m")
    endif()
endif()


function(pad_string OUT_VARIABLE DESIRED_LENGTH FILL_CHAR VALUE)
    string(LENGTH "${VALUE}" VALUE_LENGTH)
    math(EXPR REQUIRED_PADS "${DESIRED_LENGTH} - ${VALUE_LENGTH}")
    set(PAD ${VALUE})
    if(REQUIRED_PADS GREATER 0)
        math(EXPR REQUIRED_MINUS_ONE "${REQUIRED_PADS} - 1")
        foreach(FOO RANGE ${REQUIRED_MINUS_ONE})
            set(PAD "${PAD}${FILL_CHAR}")
        endforeach()
    endif()
    set(${OUT_VARIABLE} "${ColourBold}${PAD}${ColourReset}" PARENT_SCOPE)
endfunction()


function(print_target_info target_name prefix)
    if(TARGET ${target_name})
        get_target_property(INFO_INC  ${target_name} INTERFACE_INCLUDE_DIRECTORIES)
        get_target_property(INFO_LIB  ${target_name} INTERFACE_LINK_LIBRARIES)
        get_target_property(INFO_OPT  ${target_name} INTERFACE_COMPILE_OPTIONS)
        get_target_property(INFO_DEF  ${target_name} INTERFACE_COMPILE_DEFINITIONS)
        get_target_property(INFO_FTR  ${target_name} INTERFACE_COMPILE_FEATURES)
        get_target_property(TYPE_TGT  ${target_name} TYPE)
        if(NOT TYPE_TGT MATCHES "INTERFACE" AND NOT TYPE_TGT MATCHES "EXECUTABLE")
            get_target_property(INFO_LOC  ${target_name} LOCATION)
        endif()

        if(${target_name} MATCHES "CONAN")
            remove_genexpr(INFO_INC)
            remove_genexpr(INFO_LIB)
            remove_genexpr(INFO_OPT)
            remove_genexpr(INFO_DEF)
            remove_genexpr(INFO_FTR)
        endif()

        pad_string(padded_target "38" " " "${prefix}[${target_name}]" )
        if(INFO_LIB)
            list(REMOVE_DUPLICATES INFO_LIB)
            message(STATUS "${padded_target} LIBRARY : ${INFO_LIB}" )
        endif()
        if(INFO_INC)
            list(REMOVE_DUPLICATES INFO_INC)
            message(STATUS "${padded_target} INCLUDE : ${INFO_INC}" )
        endif()
        if(INFO_OPT)
            list(REMOVE_DUPLICATES INFO_OPT)
            message(STATUS "${padded_target} OPTIONS : ${INFO_OPT}" )
        endif()
        if(INFO_DEF)
            list(REMOVE_DUPLICATES INFO_DEF)
            message(STATUS "${padded_target} DEFINES : ${INFO_DEF}" )
        endif()
        if(INFO_FTR)
            message(STATUS "${padded_target} FEATURE : ${INFO_FTR}" )
        endif()
        if(INFO_LOC)
            message(STATUS "${padded_target} IMPORTS : ${INFO_LOC}" )
        endif()
    endif()
endfunction()
